language: node_js
node_js:
  - "stable"
addons:
  apt:
    packages:
      # needed by Cypress, not in Ubuntu 16+ by default
      - libconfig-2-4
cache:
  directories:
  - node_modules
  # folder with Cypress binary
  - ~/.cache
script:
  - npm run test:ci
  - npm run build
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token 1//0fe45HbbYD1pMCgYIARAAGA8SNwF-L9Ir13hKCCb4ZA9T-wI5vdtek2d8E2f4qQ6p3AQqtghyq9F6E92lQR4lxuFeODH3dVeJs84 --non-interactive
notifications:
  email:
    recipients:
      - stephanieyaur2022@u.northwestern.edu
    on_failure: always